{% set python_min = "3.10" %}
{% set version = "0.12.0" %}

package:
  name: glue-astronomy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/glue-astronomy/glue_astronomy-{{ version }}.tar.gz
  sha256: 64523eb4c7e1e53f582e96bfe81f50b1ea3413d45bce006df836db69979fc52c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:

  host:
    - python {{ python_min }}
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - setuptools
    - astropy-base >=4.0
    - glue-core >=1.6.1
    - regions >=0.4
    - specutils >=0.7
    - spectral-cube >=0.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - glue_astronomy

about:
  home: https://github.com/glue-viz/glue-astronomy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Astronomy-specific plugins for glue

extra:
  recipe-maintainers:
    - astrofrog
