{% set version = "0.3.2" %}

package:
  name: glue-astronomy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/glue-astronomy/glue-astronomy-{{ version }}.tar.gz
  sha256: 7cd75f490ca069a56502615cb7903175157af90bce07a79ddf50ff0102d531bc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >=3.6
    - setuptools
    - astropy >=4.0
    - glue-core >=1.0
    - specutils >=0.7
    - spectral-cube >=0.5
    - regions >=0.4

test:
  imports:
    - glue_astronomy

about:
  home: https://github.com/glue-viz/glue-astronomy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Astronomy-specific plugins for glue

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
