{% set version = "0.10.0" %}

package:
  name: glue-astronomy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/glue-astronomy/glue-astronomy-{{ version }}.tar.gz
  sha256: 1fdfe750c72845c7df609887d0019b890e57cfa5ac50faa73fc8bc5262082aaf

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:

  host:
    - python >=3.8
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >=3.8
    - setuptools
    - astropy-base >=4.0
    - glue-core >=1.6.1
    - regions >=0.4
    - specutils >=0.7
    - spectral-cube >=0.6.0

test:
  imports:
    - glue_astronomy

about:
  home: https://github.com/glue-viz/glue-astronomy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Astronomy-specific plugins for glue

extra:
  recipe-maintainers:
    - astrofrog
